import { SiteFooter, SiteHeader } from '../components/SiteHeader';

export default function ProfessionalsPage() {
  return <><SiteHeader /><main className="pro-page"><section className="pro-hero"><div><p className="eyebrow">Pour les professionnels de l’immobilier</p><h1>Un cadeau de clôture<br />qui ne ressemble à aucun autre.</h1><p>Offrez à vos vendeurs une expérience profondément personnelle, sans ajouter de travail à votre équipe.</p><div className="hero-actions"><a className="button" href="#packs">Découvrir les offres →</a><a className="quiet-link" href="mailto:pro@memoiremaison.ca">Parler à Émilie</a></div></div><div className="pro-portal-card"><div className="portal-head"><span>Portail professionnel</span><b>12 crédits</b></div><h3>Bonjour, Équipe Beaulieu</h3><p>Vos cadeaux de clôture, simplement.</p><div className="portal-metrics"><span><b>8</b>en création</span><span><b>3</b>à valider</span><span><b>17</b>livrés</span></div><button>＋ Inviter un vendeur</button><ul><li><i>SM</i><span><b>Sophie & Marc</b><small>Questionnaire complété</small></span><mark>72%</mark></li><li><i>AR</i><span><b>Amélie Roy</b><small>Aperçu envoyé</small></span><mark>90%</mark></li></ul></div></section>
    <section className="pro-benefits"><p className="eyebrow">Pourquoi ça fonctionne</p><h2>Plus qu’un objet. Une dernière belle étape de la transaction.</h2><div><article><span>01</span><h3>Vous invitez</h3><p>Nom, adresse et courriel. C’est tout ce qu’il vous faut pour lancer l’expérience.</p></article><article><span>02</span><h3>La famille raconte</h3><p>Elle répond, ajoute ses médias et valide son livre dans une expérience à votre image.</p></article><article><span>03</span><h3>Nous produisons</h3><p>Récit, contrôle, mise en page, impression et livraison sont pris en charge.</p></article><article><span>04</span><h3>Vous restez présent</h3><p>Votre message et votre marque accompagnent un souvenir qui durera des années.</p></article></div></section>
    <section className="packs" id="packs"><div className="section-heading"><p className="eyebrow">Packs de crédits</p><h2>Une offre qui suit votre volume.</h2><p>Chaque crédit comprend un livre Essentiel, l’invitation personnalisée et le suivi du projet.</p></div><div className="pack-grid"><article><small>DÉCOUVERTE</small><h3>10 crédits</h3><p>Pour tester avec vos prochains vendeurs.</p><b>Sur demande</b><a href="mailto:pro@memoiremaison.ca">Demander une proposition →</a></article><article className="featured"><small>LE PLUS CHOISI</small><h3>25 crédits</h3><p>Pour les courtiers actifs et petites équipes.</p><b>Tarif volume</b><a href="mailto:pro@memoiremaison.ca">Demander une proposition →</a></article><article><small>ÉQUIPE</small><h3>50+ crédits</h3><p>Pour agences, réseaux et programmes annuels.</p><b>Sur mesure</b><a href="mailto:pro@memoiremaison.ca">Construire votre programme →</a></article></div></section>
    <section className="cobrand"><div><p className="eyebrow">Votre marque, avec délicatesse</p><h2>Co-branding, message personnel et suivi en temps réel.</h2><p>La marque Mémoire Maison porte l’expérience. Votre identité trouve sa place sur l’invitation, une page dédiée dans le livre et les communications de suivi — sans jamais prendre le dessus sur l’histoire de la famille.</p></div><div className="cobrand-sample"><span>Offert avec attention par</span><b>ÉMILIE CAUVIER</b><small>COURTIÈRE IMMOBILIÈRE</small><p>« Merci de m’avoir confié un chapitre aussi important de votre histoire. »</p></div></section>
    <section className="pro-cta"><p className="eyebrow">Programme pilote Québec · Automne 2026</p><h2>Faites partie des premiers<br />professionnels partenaires.</h2><a className="button light" href="mailto:pro@memoiremaison.ca">Réserver une présentation →</a></section>
  </main><SiteFooter /></>;
}
