import { and, asc, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { getChatGPTUser } from '../../chatgpt-auth';
import { getDb } from '../../../db';
import { messages, messageThreads } from '../../../db/schema';
import { hasSupabasePublicConfig } from '../../../lib/supabase/config';
import { createSupabaseServerClient } from '../../../lib/supabase/server';
export const dynamic='force-dynamic';
export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Authentification requise'},{status:401});const threadId=new URL(request.url).searchParams.get('threadId');if(!threadId)return NextResponse.json({error:'Conversation manquante'},{status:400});if(hasSupabasePublicConfig()){const supabase=await createSupabaseServerClient();const {data,error}=await supabase!.from('messages').select('*').eq('thread_id',threadId).order('created_at',{ascending:true});if(error)return NextResponse.json({error:'Conversation introuvable'},{status:404});return NextResponse.json({messages:data})}const owned=await getDb().select({id:messageThreads.id}).from(messageThreads).where(and(eq(messageThreads.id,threadId),eq(messageThreads.userId,user.userId))).limit(1);if(!owned.length)return NextResponse.json({error:'Conversation introuvable'},{status:404});const rows=await getDb().select().from(messages).where(eq(messages.threadId,threadId)).orderBy(asc(messages.createdAt));return NextResponse.json({messages:rows})}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Authentification requise'},{status:401});const input=await request.json() as {threadId?:string;body?:string};if(!input.threadId||!input.body?.trim())return NextResponse.json({error:'Message incomplet'},{status:400});const id=crypto.randomUUID();if(hasSupabasePublicConfig()){const supabase=await createSupabaseServerClient();const {error}=await supabase!.from('messages').insert({id,thread_id:input.threadId,sender_id:user.userId,body:input.body.trim().slice(0,5000)});if(error)return NextResponse.json({error:'Conversation introuvable'},{status:404});await supabase!.from('message_threads').update({status:'waiting_team',updated_at:new Date().toISOString()}).eq('id',input.threadId);return NextResponse.json({id},{status:201})}const db=getDb();const owned=await db.select({id:messageThreads.id}).from(messageThreads).where(and(eq(messageThreads.id,input.threadId),eq(messageThreads.userId,user.userId))).limit(1);if(!owned.length)return NextResponse.json({error:'Conversation introuvable'},{status:404});await db.insert(messages).values({id,threadId:input.threadId,senderId:user.userId,body:input.body.trim().slice(0,5000),createdAt:new Date()});return NextResponse.json({id},{status:201})}
