'use client';

import { useEffect, useState } from 'react';
import Link from './SafeLink';

type Project = { client:string; address:string; status:string; progress:number; due:string; product:string };
type LuluStatus = { configured:boolean; environment:'sandbox'|'production'; ordersEnabled:boolean; product:{ podPackageId:string; name:string; trimSize:string; pageCount:number; interior:string; paper:string; cover:string } };
type SystemStatus = { database:boolean; privateStorage:boolean; authentication:boolean; serverAdministration:boolean; lulu:boolean; luluOrders:boolean; payments:boolean; transactionalEmail:boolean; bookComposition:boolean; environment:string };
const initialProjects:Project[]=[{client:'Sophie & Marc',address:'284, rue des Érables',status:'À relire',progress:72,due:'28 août',product:'Souvenir'},{client:'Amélie Roy',address:'19, avenue du Parc',status:'Aperçu envoyé',progress:90,due:'29 août',product:'Heritage'},{client:'Famille Gagnon',address:'62, chemin du Lac',status:'Photos reçues',progress:48,due:'2 sept.',product:'Famille'},{client:'Julie Tremblay',address:'731, rue Saint-Joseph',status:'En impression',progress:100,due:'4 sept.',product:'Essentiel'}];
const orders=[['MM-1048','Sophie & Marc','278 $','Payée','À produire'],['MM-1047','Amélie Roy','367 $','Payée','Aperçu approuvé'],['MM-1046','Julie Tremblay','149 $','Payée','Expédiée'],['MM-1045','Équipe Beaulieu','1 490 $','Facture','10 crédits']];
const clients=[['Sophie Martin','sophie@example.ca','2 projets','278 $'],['Amélie Roy','amelie@example.ca','1 projet','367 $'],['Marc Gagnon','marc@example.ca','1 projet','249 $'],['Julie Tremblay','julie@example.ca','3 projets','624 $']];
const menu=['Vue d’ensemble','Centre de lancement','Projets','Commandes','Utilisateurs','Professionnels','Production','Memory Links','Contenus','Finances','Visites & analytics','SEO','Newsletter','Messagerie','Paramètres'];

function Status({children}:{children:React.ReactNode}){return <mark className="status-badge">{children}</mark>}

export function AdminDashboard({name,demo=false}:{name:string;demo?:boolean}){
  const [section,setSection]=useState('Vue d’ensemble');
  const [projects,setProjects]=useState(initialProjects);
  const [showAdd,setShowAdd]=useState(false);
  const [newClient,setNewClient]=useState('');
  const [message,setMessage]=useState('');
  const [sentMessages,setSentMessages]=useState<string[]>([]);
  const [seoTitle,setSeoTitle]=useState('Mémoire Maison — Chaque maison a une histoire');
  const [newsletter,setNewsletter]=useState('');
  const [lulu,setLulu]=useState<LuluStatus|null>(null);
  const [system,setSystem]=useState<SystemStatus|null>(null);
  useEffect(()=>{let active=true;fetch('/api/lulu/status').then((response)=>response.ok?response.json() as Promise<LuluStatus>:null).then((value)=>{if(active&&value)setLulu(value)}).catch(()=>null);return()=>{active=false}},[]);
  useEffect(()=>{let active=true;fetch('/api/system/status').then((response)=>response.ok?response.json() as Promise<SystemStatus>:null).then((value)=>{if(active&&value)setSystem(value)}).catch(()=>null);return()=>{active=false}},[]);
  const addProject=()=>{if(!newClient.trim())return;setProjects((current)=>[{client:newClient,address:'Adresse à compléter',status:'Invitation à envoyer',progress:5,due:'À planifier',product:'Essentiel'},...current]);setNewClient('');setShowAdd(false)};
  const title=section==='Vue d’ensemble'?'L’atelier en un coup d’œil.':section;
  return <div className="admin-shell"><aside className="admin-sidebar"><Link className="studio-brand" href="/"><span className="brand-mark">M</span><span>Mémoire<br/>Maison</span></Link><small>{demo?'DÉMONSTRATION ADMIN':'ADMINISTRATION'}</small><nav>{menu.map((item)=><button key={item} className={section===item?'active':''} onClick={()=>setSection(item)}><span>{item==='Vue d’ensemble'?'⌂':item==='Projets'?'▤':item==='Commandes'?'□':item==='Utilisateurs'?'◎':item==='Professionnels'?'◇':item==='Production'?'◫':item==='Memory Links'?'⌁':item==='Contenus'?'✦':item==='Finances'?'$':item==='Visites & analytics'?'↗︎':item==='SEO'?'⌕':item==='Newsletter'?'✉︎':item==='Messagerie'?'◉':'⚙︎'}</span>{item}{item==='Messagerie'?<i>3</i>:null}</button>)}</nav><div className="admin-account"><span>EC</span><p><b>{name}</b><small>{demo?'Profil de démonstration':'Propriétaire · Administratrice'}</small></p></div></aside>
    <main className="admin-main"><header className="admin-top"><div><p>Bonjour {name.split(' ')[0]}</p><small>{demo?'Mode test complet · aucune action ne déclenche une vraie commande':'Accès propriétaire sécurisé · certaines intégrations restent à activer avant les ventes'}</small></div><div><Link className="admin-test-link" href="/demo/profil">Voir comme cliente</Link><button className="icon-button" onClick={()=>setSection('Messagerie')}>◉<i>3</i></button><button className="button button-small" onClick={()=>setShowAdd(true)}>＋ Ajouter</button></div></header>
      <div className={`admin-readiness-banner ${demo?'demo':''}`}><b>{demo?'Mode démonstration':lulu?.configured?'Impression Lulu connectée':'Préparation au lancement'}</b><span>{demo?'Toutes les données visibles ici sont fictives et servent à tester l’interface.':lulu?.configured?`Connexion ${lulu.environment==='production'?'production':'test'} active · validation des fichiers et tarifs disponibles${lulu.ordersEnabled?' · envoi automatique autorisé':' · envoi final verrouillé'}.`:'Les commandes, paiements, envois de courriels et impression automatique resteront désactivés jusqu’au branchement des comptes fournisseurs.'}</span>{!demo?<Link href="/demo/admin">Ouvrir la démo complète →</Link>:<Link href="/connexion">Accès propriétaire →</Link>}</div>
      <div className="admin-body"><div className="admin-title-row"><div><p className="eyebrow">Administration complète</p><h1>{title}</h1></div><div className="admin-title-actions"><select><option>Ce mois-ci</option><option>Cette semaine</option><option>Cette année</option></select><button onClick={()=>window.print()}>Exporter</button></div></div>
      {showAdd?<div className="quick-add"><div><p className="eyebrow">Ajout rapide</p><h2>Nouveau projet client</h2></div><input autoFocus value={newClient} onChange={(e)=>setNewClient(e.target.value)} placeholder="Nom du client ou de la famille"/><select><option>Projet B2C</option><option>Invitation courtier</option><option>Commande manuelle</option></select><button className="button" onClick={addProject}>Créer</button><button onClick={()=>setShowAdd(false)}>Fermer</button></div>:null}
      {section==='Vue d’ensemble'?<Overview projects={projects} open={(value)=>setSection(value)}/>:null}
      {section==='Centre de lancement'?<LaunchCenter status={system} open={setSection}/>:null}
      {section==='Projets'?<Projects projects={projects} setProjects={setProjects}/>:null}
      {section==='Commandes'?<Orders lulu={lulu}/>:null}
      {section==='Utilisateurs'?<Users/>:null}
      {section==='Professionnels'?<Professionals/>:null}
      {section==='Production'?<Production projects={projects}/>:null}
      {section==='Memory Links'?<MemoryLinks/>:null}
      {section==='Contenus'?<ContentManager/>:null}
      {section==='Finances'?<Finances/>:null}
      {section==='Visites & analytics'?<Analytics/>:null}
      {section==='SEO'?<Seo value={seoTitle} setValue={setSeoTitle}/>:null}
      {section==='Newsletter'?<Newsletter value={newsletter} setValue={setNewsletter}/>:null}
      {section==='Messagerie'?<Messaging message={message} setMessage={setMessage} sent={sentMessages} send={()=>{if(message.trim()){setSentMessages((current)=>[...current,message]);setMessage('')}}}/>:null}
      {section==='Paramètres'?<Settings/>:null}
      </div></main></div>;
}

function LaunchCenter({status,open}:{status:SystemStatus|null;open:(value:string)=>void}){
  const items=[
    ['Site FR + EN, mobile et SEO',true,'Design, navigation, métadonnées, sitemap et pages légales'],
    ['Atelier, composition et aperçu 25 pages',true,'Photos, films, voix, édition page par page et validation'],
    ['Comptes clients sans mot de passe',Boolean(status?.authentication),'Se branche dès que les 3 variables Supabase sont ajoutées'],
    ['Base clients, projets et commandes',Boolean(status?.database),'Schéma, index et sécurité par utilisateur déjà préparés'],
    ['Médias privés multi-appareils',Boolean(status?.privateStorage),'Stockage privé et droits d’accès déjà préparés'],
    ['Administration reliée aux données',Boolean(status?.serverAdministration),'Nécessite la clé serveur Supabase'],
    ['Composition éditoriale',Boolean(status?.bookComposition),'Solution de repli active même sans fournisseur externe'],
    ['Lulu Print API',Boolean(status?.lulu),'Tarifs, validation des fichiers et suivi sont codés'],
    ['Envoi réel à Lulu',Boolean(status?.luluOrders),'Verrouillé tant que les essais et contrôles ne sont pas validés'],
    ['Courriels transactionnels',Boolean(status?.transactionalEmail),'Modèles et domaine d’envoi à brancher'],
    ['Paiement Stripe',Boolean(status?.payments),'Volontairement reporté jusqu’au compte d’Emilie'],
  ] as const;
  const ready=items.filter((item)=>item[1]).length;
  return <div className="admin-module launch-center"><section className="launch-hero panel"><div><p className="eyebrow">Préparation commerciale</p><h2>{ready} éléments sur {items.length} prêts</h2><p>Le code peut être finalisé sans lancer de vente. Les commandes réelles restent verrouillées jusqu’aux comptes fournisseurs et aux essais physiques.</p></div><div className="launch-score"><b>{Math.round(ready/items.length*100)}%</b><small>technique</small></div></section><div className="launch-checklist">{items.map(([label,done,detail])=><article className={`panel ${done?'ready':'waiting'}`} key={label}><span>{done?'✓':'○'}</span><div><h3>{label}</h3><p>{detail}</p></div><mark>{done?'Prêt':'À connecter'}</mark></article>)}</div><section className="module-grid"><article className="panel"><h2>Actions disponibles maintenant</h2><ul className="check-list"><li>✓ Tester tout le parcours client en démo</li><li>✓ Créer et modifier un livre complet</li><li>✓ Ajouter photos, vidéos et voix</li><li>✓ Vérifier le rendu mobile et l’aperçu imprimable</li><li>✓ Préparer les clés Lulu en environnement test</li></ul></article><article className="panel"><h2>Verrous de sécurité</h2><ul className="check-list"><li>✓ Aucun envoi à l’imprimeur sans approbation</li><li>✓ Aucun paiement tant que Stripe n’est pas branché</li><li>✓ Médias privés par propriétaire</li><li>✓ Rôle admin séparé des clients</li><li>✓ Journal d’audit prévu dans la base</li></ul><button onClick={()=>open('Paramètres')}>Voir les paramètres →</button></article></section></div>
}

function Overview({projects,open}:{projects:Project[];open:(value:string)=>void}){return <><section className="metric-grid"><article><span className="metric-icon sage">▤</span><p>Projets actifs</p><b>{projects.length+20}</b><small><i>+ 12 %</i> vs mois dernier</small></article><article><span className="metric-icon gold">□</span><p>À valider aujourd’hui</p><b>6</b><small>3 aperçus · 3 récits</small></article><article><span className="metric-icon clay">$</span><p>Chiffre d’affaires</p><b>8 642 $</b><small><i>+ 18 %</i> vs mois dernier</small></article><article><span className="metric-icon ink">◇</span><p>Crédits B2B utilisés</p><b>37 / 65</b><small>8 courtiers actifs</small></article></section><section className="admin-grid"><article className="panel project-panel"><div className="panel-head"><div><h2>Projets à suivre</h2><p>Les dossiers qui demandent votre attention</p></div><button onClick={()=>open('Projets')}>Voir tous →</button></div><ProjectTable projects={projects}/></article><article className="panel activity-panel"><div className="panel-head"><div><h2>Activité récente</h2><p>Les dernières 24 heures</p></div></div><ul><li><span>✓</span><p><b>Aperçu approuvé</b><small>Amélie Roy · il y a 18 min</small></p></li><li><span>▧</span><p><b>18 photos ajoutées</b><small>Famille Gagnon · il y a 1 h</small></p></li><li><span>$</span><p><b>Commande de 278 $</b><small>Sophie & Marc · il y a 3 h</small></p></li><li><span>◇</span><p><b>10 crédits achetés</b><small>Équipe Beaulieu · hier</small></p></li></ul></article></section><section className="admin-grid lower"><article className="panel production-panel"><div className="panel-head"><div><h2>Chaîne de production</h2><p>32 projets en circulation</p></div><button onClick={()=>open('Production')}>Ouvrir →</button></div><div className="pipeline">{[['Questionnaire',8],['Récit & contrôle',6],['Mise en page',7],['Validation',5],['Impression',4],['Expédition',2]].map(([label,count])=><div key={label}><b>{count}</b><span>{label}</span></div>)}</div></article><article className="panel b2b-panel"><div><p className="eyebrow">B2B</p><h2>3 invitations vendeurs<br/>à relancer</h2><p>Deux crédits expirent dans moins de 30 jours.</p><button onClick={()=>open('Professionnels')}>Ouvrir le portail pro →</button></div><span className="credit-ring">57%<small>crédits<br/>utilisés</small></span></article></section></>}

function ProjectTable({projects}:{projects:Project[]}){return <div className="project-table"><div className="table-head"><span>Client & propriété</span><span>Offre</span><span>Progression</span><span>Statut</span><span>Échéance</span></div>{projects.map((project)=><div className="table-row" key={`${project.client}-${project.address}`}><span><i>{project.client.split(' ').map((word)=>word[0]).join('').slice(0,2)}</i><b>{project.client}<small>{project.address}</small></b></span><span>{project.product}</span><span><em><i style={{width:`${project.progress}%`}}/></em>{project.progress}%</span><span><Status>{project.status}</Status></span><span>{project.due}</span></div>)}</div>}
function Projects({projects,setProjects}:{projects:Project[];setProjects:React.Dispatch<React.SetStateAction<Project[]>>}){return <div className="admin-module"><div className="module-toolbar"><input placeholder="Rechercher un client ou une adresse"/><select><option>Tous les statuts</option><option>À relire</option><option>Aperçu envoyé</option><option>En impression</option></select><button className="button button-small" onClick={()=>setProjects((current)=>[{client:'Nouveau client',address:'À compléter',status:'Brouillon',progress:0,due:'À planifier',product:'Essentiel'},...current])}>＋ Projet</button></div><article className="panel"><ProjectTable projects={projects}/></article><div className="module-grid"><article className="panel"><h2>Contrôle anti-invention</h2><p>Chaque récit doit passer la fiche de faits, le contrôle automatique, la validation humaine et l’approbation du client.</p><ul className="check-list"><li>✓ 14 récits conformes</li><li>! 2 ambiguïtés à vérifier</li><li>○ 4 contrôles à lancer</li></ul></article><article className="panel"><h2>Actions en lot</h2><button>Envoyer les rappels</button><button>Exporter les médias</button><button>Assigner à un membre</button></article></div></div>}
function Orders({lulu}:{lulu:LuluStatus|null}){return <div className="admin-module"><div className="metric-grid mini"><article><p>Commandes ce mois</p><b>48</b></article><article><p>Panier moyen</p><b>183 $</b></article><article><p>À rembourser</p><b>1</b></article><article><p>Réimpressions</p><b>2</b></article></div><article className="panel admin-data-table"><div className="data-row header"><span>Commande</span><span>Client</span><span>Total</span><span>Paiement</span><span>Production</span><span>Actions</span></div>{orders.map((row)=><div className="data-row" key={row[0]}>{row.map((cell,index)=><span key={cell}>{index>2&&index<5?<Status>{cell}</Status>:cell}</span>)}<span><button>Voir</button><button>•••</button></span></div>)}</article><div className="module-grid"><article className="panel"><h2>Règles de commande</h2><p>Impression impossible tant que l’aperçu n’est pas approuvé. Les corrections et la validation sont horodatées.</p><Status>Verrou actif</Status></article><article className="panel lulu-provider"><div className="panel-head"><div><h2>Lulu Print API</h2><p>{lulu?.configured?`Connexion ${lulu.environment==='production'?'production':'test'} active`:'Connexion en attente de la clé'}</p></div><Status>{lulu?.configured?'Connecté':'À relier'}</Status></div><div className="lulu-product"><span className="lulu-book-mark">M²</span><p><b>{lulu?.product.name||'Livre photo carré — Couverture rigide'}</b><small>{lulu?.product.trimSize||'21,6 × 21,6 cm'} · {lulu?.product.interior||'Couleur premium'}<br/>{lulu?.product.paper||'Papier blanc couché 80 lb'} · finition mate</small></p></div><ol className="provider-steps"><li className="done">Aperçu approuvé</li><li>PDF intérieur contrôlé</li><li>Couverture calculée</li><li>Tarif + livraison</li><li>Impression et suivi</li></ol><p className="provider-lock">{lulu?.ordersEnabled?'Envoi automatique autorisé après tous les contrôles.':'Sécurité active : aucune impression réelle ne part sans activation explicite.'}</p></article></div></div>}
function Users(){return <div className="admin-module"><div className="module-toolbar"><input placeholder="Rechercher un utilisateur"/><select><option>Tous les rôles</option><option>Client</option><option>Courtier</option><option>Équipe</option><option>Administrateur</option></select><button className="button button-small">＋ Inviter</button></div><article className="panel admin-data-table"><div className="data-row users-row header"><span>Utilisateur</span><span>Rôle</span><span>Projets</span><span>Dépenses</span><span>Dernière activité</span><span>Actions</span></div>{clients.map((client,index)=><div className="data-row users-row" key={client[1]}><span><i className="avatar">{client[0].split(' ').map((word)=>word[0]).join('')}</i><b>{client[0]}<small>{client[1]}</small></b></span><span><select defaultValue={index===3?'Courtier':'Client'}><option>Client</option><option>Courtier</option><option>Éditeur</option><option>Admin</option></select></span><span>{client[2]}</span><span>{client[3]}</span><span>Il y a {index+1} h</span><span><button>Ouvrir</button><button>•••</button></span></div>)}</article><div className="permission-card panel"><h2>Rôles & permissions</h2><div><span><b>Propriétaire</b><small>Tout voir et tout modifier, accès facturation et sécurité.</small></span><span><b>Administrateur</b><small>Utilisateurs, commandes, contenu, messages et production.</small></span><span><b>Éditeur</b><small>Récits, médias, aperçus et contenu marketing.</small></span><span><b>Client</b><small>Uniquement ses projets, commandes et Memory Links.</small></span></div></div></div>}
function Professionals(){return <div className="admin-module"><div className="metric-grid mini"><article><p>Comptes actifs</p><b>8</b></article><article><p>Crédits vendus</p><b>65</b></article><article><p>Crédits utilisés</p><b>37</b></article><article><p>Renouvellements</p><b>82%</b></article></div><div className="module-grid"><article className="panel"><div className="panel-head"><div><h2>Équipe Beaulieu</h2><p>25 crédits · Co-branding actif</p></div><Status>Actif</Status></div><div className="pro-credit-bar"><i style={{width:'68%'}}/></div><p>17 utilisés · 8 disponibles · expiration 31 déc. 2026</p><button>Gérer le compte</button></article><article className="panel"><h2>Créer une offre B2B</h2><label>Nombre de crédits<input defaultValue="25"/></label><label>Rabais volume<input defaultValue="12 %"/></label><label>Marque<select><option>Co-branding</option><option>White-label</option></select></label><button className="button button-small">Créer la proposition</button></article></div><article className="panel"><h2>Invitations vendeurs</h2><div className="data-row header"><span>Professionnel</span><span>Vendeur</span><span>Invitation</span><span>Projet</span><span>Action</span></div>{[['Équipe Beaulieu','Sophie Martin','Ouverte','72%'],['Emilie Cauvier','Marc Gagnon','Complétée','48%'],['Groupe Horizon','Julie Roy','À relancer','0%']].map((row)=><div className="data-row five" key={row[1]}>{row.map((cell)=><span key={cell}>{cell}</span>)}<span><button>Relancer</button></span></div>)}</article></div>}
function Production({projects}:{projects:Project[]}){const cols=['Questionnaire','Récit & contrôle','Mise en page','Validation client','Impression','Expédition'];return <div className="admin-module"><div className="production-board">{cols.map((col,index)=><section key={col}><header><b>{col}</b><span>{index+2}</span></header>{projects.slice(0,index%2?2:3).map((p)=><article key={`${col}-${p.client}`}><small>{p.product}</small><h3>{p.client}</h3><p>{p.address}</p><footer><Status>{index===3?'Aperçu requis':p.status}</Status><button>•••</button></footer></article>)}<button>＋ Ajouter une carte</button></section>)}</div></div>}
function MemoryLinks(){return <div className="admin-module"><div className="module-toolbar"><input placeholder="Rechercher une archive"/><select><option>Tous les accès</option><option>Privé</option><option>Code PIN</option><option>Expiré</option></select><button className="button button-small">＋ Memory Link</button></div><div className="memory-admin-grid">{[['La maison des Érables','Sophie & Marc','128 vues','Actif'],['Maison de famille Roy','Amélie Roy','67 vues','Code PIN'],['Notre premier chez-nous','Julie Tremblay','34 vues','Actif']].map((item)=><article className="panel" key={item[0]}><div className="memory-admin-cover">MM</div><small>MEMORY LINK</small><h2>{item[0]}</h2><p>{item[1]} · {item[2]}</p><Status>{item[3]}</Status><div><button>Ouvrir</button><button>Modifier</button><button>QR</button></div></article>)}</div><article className="panel"><h2>Conservation & consentements</h2><div className="settings-row"><span><b>Rappel avant expiration</b><small>Notifier la famille 60 et 15 jours avant la fin de l’hébergement.</small></span><button className="toggle on">●</button></div><div className="settings-row"><span><b>Ajout après livraison</b><small>Autoriser les propriétaires à enrichir leur archive.</small></span><button className="toggle on">●</button></div></article></div>}
function ContentManager(){return <div className="admin-module"><div className="module-grid"><article className="panel"><div className="panel-head"><div><h2>Pages du site</h2><p>FR et EN synchronisés</p></div><button>＋ Page</button></div>{[['Accueil','Publié','FR · EN'],['Comment ça marche','Publié','FR · EN'],['Professionnels','Publié','FR · EN'],['FAQ','Publié','FR · EN'],['Conditions générales','Brouillon','FR · EN']].map((row)=><div className="content-row" key={row[0]}><span><b>{row[0]}</b><small>Modifié aujourd’hui</small></span><Status>{row[1]}</Status><span>{row[2]}</span><button>Modifier</button></div>)}</article><article className="panel"><h2>Bibliothèque de médias</h2><div className="media-grid">{Array.from({length:6}).map((_,i)=><button key={i} className={`media-swatch m${i}`}>Photo {i+1}</button>)}</div><button className="button button-small">Téléverser</button></article></div><article className="panel editor-mock"><div><label>Titre<input defaultValue="10 souvenirs à photographier avant de déménager"/></label><label>Extrait<textarea defaultValue="Une checklist douce pour ne pas oublier les détails qui font d’une maison un foyer."/></label><label>Langue<select><option>Français</option><option>English</option></select></label></div><div><h2>Aperçu de l’article</h2><div className="article-preview"><p className="eyebrow">GUIDE</p><h3>10 souvenirs à photographier avant de déménager</h3><p>Une checklist douce pour ne pas oublier les détails qui font d’une maison un foyer.</p></div><button className="button button-small">Publier</button></div></article></div>}
function Finances(){return <div className="admin-module"><div className="metric-grid"><article><p>Revenus nets</p><b>8 642 $</b><small>Août 2026</small></article><article><p>Marge estimée</p><b>54%</b><small>Après POD et paiement</small></article><article><p>Panier moyen</p><b>183 $</b><small>Objectif 180 $</small></article><article><p>CAC moyen</p><b>27 $</b><small>Objectif &lt; 30 $</small></article></div><div className="module-grid"><article className="panel"><h2>Revenus par semaine</h2><div className="chart-bars">{[42,55,48,72,66,88,78,95].map((value,i)=><i key={i} style={{height:`${value}%`}}><span>{value*20}$</span></i>)}</div></article><article className="panel"><h2>Économie unitaire</h2>{[['Prix moyen','183 $'],['Impression','- 32 $'],['Livraison','- 13 $'],['Technologie & paiement','- 8 $'],['Acquisition','- 27 $'],['Contribution','103 $']].map((row)=><div className="finance-row" key={row[0]}><span>{row[0]}</span><b>{row[1]}</b></div>)}</article></div></div>}
function Analytics(){return <div className="admin-module"><div className="metric-grid"><article><p>Visiteurs uniques</p><b>4 821</b><small><i>+ 24 %</i></small></article><article><p>Créations démarrées</p><b>386</b><small>8,0 % des visites</small></article><article><p>Commandes</p><b>48</b><small>12,4 % des projets</small></article><article><p>Conversion globale</p><b>1,0 %</b><small><i>+ 0,2 pt</i></small></article></div><div className="module-grid analytics-grid"><article className="panel"><div className="panel-head"><div><h2>Trafic sur 30 jours</h2><p>Visites FR + EN</p></div><select><option>Visiteurs</option><option>Pages vues</option></select></div><div className="line-chart"><span style={{height:'35%'}}/><span style={{height:'45%'}}/><span style={{height:'42%'}}/><span style={{height:'62%'}}/><span style={{height:'54%'}}/><span style={{height:'70%'}}/><span style={{height:'65%'}}/><span style={{height:'82%'}}/><span style={{height:'75%'}}/><span style={{height:'94%'}}/></div></article><article className="panel"><h2>Sources</h2>{[['Instagram','38%'],['Recherche Google','24%'],['Courtiers partenaires','19%'],['Accès direct','12%'],['Newsletter','7%']].map((row)=><div className="source-row" key={row[0]}><span>{row[0]}</span><em><i style={{width:row[1]}}/></em><b>{row[1]}</b></div>)}</article></div><article className="panel"><h2>Parcours de conversion</h2><div className="funnel"><span><b>4 821</b>Visites</span><span><b>1 204</b>Offres vues</span><span><b>386</b>Ateliers démarrés</span><span><b>124</b>Aperçus créés</span><span><b>48</b>Commandes</span></div></article></div>}
function Seo({value,setValue}:{value:string;setValue:(value:string)=>void}){return <div className="admin-module"><div className="seo-score"><div><b>92</b><small>/100</small></div><span><h2>Très bonne santé SEO</h2><p>11 pages indexables · 0 erreur critique · 3 améliorations suggérées</p></span></div><div className="module-grid"><article className="panel seo-editor"><h2>Page d’accueil · Français</h2><label>Titre SEO<input value={value} onChange={(e)=>setValue(e.target.value)}/><small>{value.length}/60 caractères</small></label><label>Description<textarea defaultValue="Créez un livre souvenir personnalisé de votre maison, à partir de vos photos, de vos mots et de votre voix."/><small>128/160 caractères</small></label><label>URL canonique<input defaultValue="/"/></label><button className="button button-small">Enregistrer</button></article><article className="panel"><h2>Aperçu Google</h2><div className="google-preview"><span>memoiremaison.ca</span><h3>{value}</h3><p>Créez un livre souvenir personnalisé de votre maison, à partir de vos photos, de vos mots et de votre voix.</p></div><h2>Contrôles</h2><ul className="check-list"><li>✓ Carte de partage 1200 × 630</li><li>✓ Version anglaise reliée</li><li>✓ Titres et descriptions uniques</li><li>! Ajouter l’adresse légale définitive</li></ul></article></div><article className="panel"><h2>Pages & indexation</h2>{[['/','Chaque maison a une histoire','Indexée','FR'],['/en','Every home has a story','Indexée','EN'],['/professionnels','Pour les professionnels','Indexée','FR'],['/atelier','Atelier de création','Noindex','FR'],['/profil','Espace client','Privée','FR/EN']].map((row)=><div className="seo-row" key={row[0]}>{row.map((cell)=><span key={cell}>{cell}</span>)}<button>Modifier</button></div>)}</article></div>}
function Newsletter({value,setValue}:{value:string;setValue:(value:string)=>void}){return <div className="admin-module"><div className="metric-grid mini"><article><p>Abonnés</p><b>2 416</b></article><article><p>Taux d’ouverture</p><b>48,2%</b></article><article><p>Taux de clic</p><b>6,7%</b></article><article><p>Désabonnements</p><b>0,3%</b></article></div><div className="module-grid newsletter-grid"><article className="panel"><h2>Nouvelle campagne</h2><label>Segment<select><option>Tous les abonnés</option><option>Propriétaires</option><option>Courtiers</option><option>Partenaires</option></select></label><label>Objet<input value={value} onChange={(e)=>setValue(e.target.value)} placeholder="Avant de tourner la page…"/></label><label>Pré-en-tête<input placeholder="Une histoire à garder pour toujours"/></label><label>Message<textarea rows={8} placeholder="Écrivez votre lettre…"/></label><div className="button-row"><button>Brouillon</button><button>Envoyer un test</button><button className="button button-small">Planifier →</button></div></article><article className="panel"><h2>Conformité LCAP</h2><ul className="check-list"><li>✓ Consentement explicite enregistré</li><li>✓ Identité de l’expéditeur</li><li>✓ Adresse postale requise avant envoi</li><li>✓ Désabonnement en un clic</li></ul><h2>Segments</h2>{[['Propriétaires','1 684'],['Courtiers','522'],['Partenaires','210']].map((row)=><div className="finance-row" key={row[0]}><span>{row[0]}</span><b>{row[1]}</b></div>)}</article></div><article className="panel"><h2>Campagnes récentes</h2><div className="data-row five header"><span>Campagne</span><span>Segment</span><span>Envoi</span><span>Ouverture</span><span>Statut</span></div>{[['Le dernier été dans la maison','Propriétaires','18 août','51,2%','Envoyée'],['Programme pilote courtiers','Courtiers','12 août','44,8%','Envoyée'],['Notre Maison arrive bientôt','Tous','29 août','—','Planifiée']].map((row)=><div className="data-row five" key={row[0]}>{row.map((cell,index)=><span key={cell}>{index===4?<Status>{cell}</Status>:cell}</span>)}</div>)}</article></div>}
function Messaging({message,setMessage,sent,send}:{message:string;setMessage:(value:string)=>void;sent:string[];send:()=>void}){return <div className="messaging-shell"><aside className="inbox-list"><div className="inbox-head"><h2>Messages</h2><button>＋</button></div><input placeholder="Rechercher"/>{[['Sophie Martin','J’ai une question sur l’aperçu…','2 min','2'],['Amélie Roy','Merci, c’est exactement ça','1 h',''],['Équipe Beaulieu','Peut-on ajouter notre logo ?','3 h','1'],['Julie Tremblay','La nouvelle photo est envoyée.','Hier','']].map((row,index)=><button className={index===0?'active':''} key={row[0]}><i>{row[0].split(' ').map((word)=>word[0]).join('')}</i><span><b>{row[0]}</b><small>{row[1]}</small></span><em>{row[2]}{row[3]?<mark>{row[3]}</mark>:null}</em></button>)}</aside><section className="conversation"><header><i>SM</i><span><b>Sophie Martin</b><small>Projet · La maison des Érables</small></span><button>Voir le profil</button><button>•••</button></header><div className="messages"><p className="received">Bonjour ! J’ai reçu l’aperçu, il est vraiment beau. J’aimerais seulement changer une photo dans le chapitre 2.</p><p className="sent">Bien sûr Sophie. Tu peux cliquer sur « Changer une photo » directement dans l’aperçu, ou me l’envoyer ici.</p><p className="received">Parfait, est-ce que ça retarde l’impression ?</p>{sent.map((item)=><p className="sent" key={item}>{item}</p>)}</div><div className="message-composer"><button>＋</button><button>▧</button><textarea value={message} onChange={(e)=>setMessage(e.target.value)} placeholder="Écrire un message…" onKeyDown={(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button onClick={send}>Envoyer</button></div></section><aside className="contact-panel"><div className="contact-avatar">SM</div><h2>Sophie Martin</h2><p>sophie@example.ca</p><button className="button button-small">Ouvrir le projet</button><h3>Commande</h3><span><b>MM-1048</b><small>Souvenir + Memory Link</small></span><span><b>278 $ CAD</b><small>Payée</small></span><h3>Fichiers partagés</h3><div className="shared-files"><i/><i/><i/></div></aside></div>}
function Settings(){return <div className="admin-module settings-module"><nav><button className="active">Entreprise</button><button>Équipe & rôles</button><button>Production</button><button>Paiements</button><button>Livraison</button><button>Notifications</button><button>Confidentialité</button><button>Intégrations</button></nav><section><article className="panel"><h2>Identité de l’entreprise</h2><div className="form-grid"><label>Nom commercial<input defaultValue="Mémoire Maison"/></label><label>Entité légale<input defaultValue="Emilie Cauvier Inc."/></label><label>Courriel public<input defaultValue="emilie@equipecauvier.com"/></label><label>Téléphone<input placeholder="À compléter"/></label><label className="wide">Adresse légale<textarea placeholder="À compléter avant l’ouverture des ventes"/></label></div><button className="button button-small">Enregistrer</button></article><article className="panel"><h2>Flux de validation avant impression</h2>{[['Aperçu client obligatoire',true],['Approbation horodatée',true],['Validation humaine interne',true],['Impression automatique après approbation',false]].map(([label,on])=><div className="settings-row" key={String(label)}><span><b>{label}</b><small>{label==='Aperçu client obligatoire'?'Aucune commande ne peut être envoyée au fournisseur sans approbation explicite.':'Règle modifiable par la propriétaire.'}</small></span><button className={`toggle ${on?'on':''}`}>●</button></div>)}</article><article className="panel danger-zone"><h2>Sécurité & données</h2><p>Authentification administrateur par compte propriétaire Sites/ChatGPT. Aucun mot de passe partagé n’est conservé.</p><button>Exporter toutes les données</button><button>Journal des accès</button><button>Gérer la conservation des médias</button></article></section></div>}

