'use client';

import Link from './SafeLink';
import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { BOOK_STORAGE_KEY, fallbackBook, type BookLocale, type BookPage, type GeneratedBook } from '../../lib/book';

function initialBook(locale: BookLocale) {
  return fallbackBook({ locale, title: locale === 'en' ? 'Our Home' : 'Notre Maison', subtitle: '2008 — 2026', address: '', collection: locale === 'en' ? 'Essential' : 'Essentiel', coverColor: 'forest', answers: {}, media: [] });
}

export function BookPreview({ locale = 'fr' }: { locale?: BookLocale }) {
  const en = locale === 'en'; const [book, setBook] = useState<GeneratedBook>(() => initialBook(locale)); const [spread, setSpread] = useState(0); const [selectedSide, setSelectedSide] = useState<0 | 1>(0); const [confirmed, setConfirmed] = useState(false); const [approved, setApproved] = useState(false); const [panel, setPanel] = useState<'edit' | 'media' | null>(null); const [saveState, setSaveState] = useState<'saved' | 'saving'>('saved');
  const profile = en ? '/en/profile' : '/profil'; const studio = en ? '/en/studio' : '/atelier';

  useEffect(() => {
    let cancelled = false;
    const restore = async () => {
      try { const stored = sessionStorage.getItem(BOOK_STORAGE_KEY) || localStorage.getItem(BOOK_STORAGE_KEY); if (stored) { const parsed = JSON.parse(stored); if (!cancelled) setBook(parsed); return; } } catch { /* fetch persisted copy */ }
      const projectId = new URL(window.location.href).searchParams.get('project');
      if (!projectId) return;
      const response = await fetch(`/api/book-generations?projectId=${encodeURIComponent(projectId)}`);
      if (response.ok) { const result = (await response.json()) as { generation: { result: GeneratedBook } }; if (!cancelled) setBook(result.generation.result); }
    };
    restore(); return () => { cancelled = true; };
  }, []);
  useEffect(() => {
    const savingTimer = window.setTimeout(() => setSaveState('saving'), 0);
    const timer = window.setTimeout(async () => {
      const next = { ...book, updatedAt: new Date().toISOString() };
      sessionStorage.setItem(BOOK_STORAGE_KEY, JSON.stringify(next));
      try { localStorage.setItem(BOOK_STORAGE_KEY, JSON.stringify(next)); } catch { /* session copy remains */ }
      if (book.projectId) await fetch(`/api/book-generations/${encodeURIComponent(book.id)}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ book: next, version: book.version, status: book.status }) });
      setSaveState('saved');
    }, 700);
    return () => { window.clearTimeout(savingTimer); window.clearTimeout(timer); };
  }, [book]);

  const spreads = useMemo(() => Array.from({ length: Math.ceil(book.pages.length / 2) }, (_, index) => book.pages.slice(index * 2, index * 2 + 2)), [book.pages]);
  const current = spreads[spread] || []; const selectedIndex = Math.min(spread * 2 + selectedSide, book.pages.length - 1); const selectedPage = book.pages[selectedIndex];
  const updatePage = (changes: Partial<BookPage>) => setBook((currentBook) => ({ ...currentBook, version: currentBook.version + 1, pages: currentBook.pages.map((page, index) => index === selectedIndex ? { ...page, ...changes } : page) }));
  const movePage = (direction: -1 | 1) => setBook((currentBook) => { const target = selectedIndex + direction; if (target < 1 || target >= currentBook.pages.length) return currentBook; const pages = [...currentBook.pages]; [pages[selectedIndex], pages[target]] = [pages[target], pages[selectedIndex]]; window.setTimeout(() => { setSpread(Math.floor(target / 2)); setSelectedSide((target % 2) as 0 | 1); }, 0); return { ...currentBook, version: currentBook.version + 1, pages }; });
  const addMedia = (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []); const additions = files.map((file) => ({ id: crypto.randomUUID(), name: file.name, kind: 'photo' as const, previewUrl: URL.createObjectURL(file) })); setBook((currentBook) => ({ ...currentBook, version: currentBook.version + 1, media: [...currentBook.media, ...additions], pages: currentBook.pages.map((page, index) => index === selectedIndex ? { ...page, mediaIds: [...page.mediaIds, ...additions.map((item) => item.id)].slice(0, 6) } : page) })); event.target.value = ''; };
  const toggleMedia = (id: string) => updatePage({ mediaIds: selectedPage.mediaIds.includes(id) ? selectedPage.mediaIds.filter((item) => item !== id) : [...selectedPage.mediaIds, id].slice(0, 6) });
  const approve = async () => { const versionHash = `${book.id}-v${book.version}-${book.updatedAt}`; if (book.projectId) await fetch('/api/approvals', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId: book.projectId, versionHash }) }); setBook((value) => ({ ...value, status: 'approved' })); setApproved(true); };

  return <main className="preview-shell"><header className="preview-top"><Link className="brand" href={profile}><span className="brand-mark">M</span><span>Mémoire Maison</span></Link><div className="preview-progress"><span className="done">✓ {en ? 'Creation' : 'Création'}</span><i /><span className="active">2 {en ? 'Preview' : 'Aperçu'}</span><i /><span>3 {en ? 'Print' : 'Impression'}</span><i /><span>4 {en ? 'Delivery' : 'Livraison'}</span></div><span className={`save-indicator ${saveState}`}>{saveState === 'saved' ? `✓ ${en ? 'Saved' : 'Enregistré'}` : en ? 'Saving…' : 'Enregistrement…'}</span></header>
    <section className="preview-workspace"><aside className="preview-tools"><p className="eyebrow">{en ? 'Your digital proof' : 'Votre aperçu numérique'}</p><h1>{en ? 'Review and make it yours.' : 'Relisez et faites-le vôtre.'}</h1><p>{en ? 'Select a page, then edit its words, layout or images. Nothing goes to print without your approval.' : 'Sélectionnez une page, puis modifiez ses mots, sa mise en page ou ses images. Rien ne part à l’impression sans votre accord.'}</p><div className="preview-checks"><span>✓ {en ? 'Every fact comes from your answers' : 'Chaque fait vient de vos réponses'}</span><span>✓ {en ? 'All text remains editable' : 'Tous les textes restent modifiables'}</span><span>✓ {en ? 'Premium square format · 24 pages minimum' : 'Format carré premium · 24 pages minimum'}</span><span>✓ {en ? 'Print files are checked before production' : 'Fichiers contrôlés avant fabrication'}</span></div><button type="button" className={panel === 'edit' ? 'active' : ''} onClick={() => setPanel(panel === 'edit' ? null : 'edit')}>✎ {en ? 'Edit this page' : 'Modifier cette page'}</button><button type="button" className={panel === 'media' ? 'active' : ''} onClick={() => setPanel(panel === 'media' ? null : 'media')}>▧ {en ? 'Photos on this page' : 'Photos de cette page'}</button><button type="button" onClick={() => window.print()}>⇩ {en ? 'Print / save as PDF' : 'Imprimer / enregistrer en PDF'}</button><Link href={studio}>← {en ? 'Return to my answers' : 'Revenir à mes réponses'}</Link></aside>
      <div className="book-stage"><div className={`open-book color-${book.coverColor}`}>{[0, 1].map((side) => { const page = current[side]; return <article key={page?.id || side} tabIndex={page ? 0 : -1} className={`book-page ${side === 0 ? 'left-page' : 'right-page'} ${selectedSide === side ? 'selected' : ''} layout-${page?.layout || 'minimal'}`} onClick={() => page && setSelectedSide(side as 0 | 1)}>{page ? <PageContent page={page} book={book} en={en} /> : null}</article>; })}</div><p className="page-select-hint">{en ? 'Tap a page to edit it' : 'Touchez une page pour la modifier'}</p><div className="page-controls"><button onClick={() => { setSpread(Math.max(0, spread - 1)); setSelectedSide(0); }} disabled={spread === 0}>←</button><span>{en ? 'Pages' : 'Pages'} {spread * 2 + 1}—{Math.min(book.pages.length, spread * 2 + 2)} / {book.pages.length}</span><button onClick={() => { setSpread(Math.min(spreads.length - 1, spread + 1)); setSelectedSide(0); }} disabled={spread === spreads.length - 1}>→</button></div><div className="thumbnail-strip">{spreads.map((pages, index) => <button key={pages[0]?.id || index} className={spread === index ? 'active' : ''} onClick={() => { setSpread(index); setSelectedSide(0); }}><i className={`thumb-${pages[0]?.kind || 'story'}`} /><span>{index * 2 + 1}</span></button>)}</div></div>
      {panel && selectedPage && <aside className="page-editor"><header><div><small>{en ? 'Selected page' : 'Page sélectionnée'} {selectedIndex + 1}</small><b>{selectedPage.title}</b></div><button onClick={() => setPanel(null)} aria-label={en ? 'Close' : 'Fermer'}>×</button></header>{panel === 'edit' ? <><label>{en ? 'Small heading' : 'Petit titre'}<input value={selectedPage.eyebrow || ''} onChange={(event) => updatePage({ eyebrow: event.target.value })} /></label><label>{en ? 'Page title' : 'Titre de la page'}<input value={selectedPage.title} onChange={(event) => updatePage({ title: event.target.value })} /></label><label>{en ? 'Story' : 'Récit'}<textarea value={selectedPage.body} onChange={(event) => updatePage({ body: event.target.value })} /></label><label>{en ? 'Quote (optional)' : 'Citation (facultative)'}<textarea value={selectedPage.quote || ''} onChange={(event) => updatePage({ quote: event.target.value })} /></label><fieldset><legend>{en ? 'Layout' : 'Mise en page'}</legend><div className="layout-choices">{(['editorial', 'full-photo', 'split', 'collage', 'minimal'] as const).map((layout) => <button type="button" key={layout} className={selectedPage.layout === layout ? 'active' : ''} onClick={() => updatePage({ layout })}>{layout === 'editorial' ? (en ? 'Editorial' : 'Éditoriale') : layout === 'full-photo' ? (en ? 'Full image' : 'Grande image') : layout === 'split' ? (en ? 'Split' : 'Partagée') : layout === 'collage' ? 'Collage' : (en ? 'Minimal' : 'Épurée')}</button>)}</div></fieldset><div className="page-order"><button onClick={() => movePage(-1)} disabled={selectedIndex <= 1}>← {en ? 'Move before' : 'Déplacer avant'}</button><button onClick={() => movePage(1)} disabled={selectedIndex >= book.pages.length - 1}>{en ? 'Move after' : 'Déplacer après'} →</button></div></> : <><label className="editor-upload"><input type="file" accept="image/*" multiple onChange={addMedia} />＋ {en ? 'Add photos' : 'Ajouter des photos'}</label><div className="editor-media-grid">{book.media.filter((item) => item.kind === 'photo').map((item) => <button key={item.id} type="button" className={selectedPage.mediaIds.includes(item.id) ? 'active' : ''} onClick={() => toggleMedia(item.id)}>{item.previewUrl ? <img src={item.previewUrl} alt={item.name} /> : <span>▧</span>}<small>{selectedPage.mediaIds.includes(item.id) ? '✓ ' : ''}{item.name}</small></button>)}</div>{!book.media.some((item) => item.kind === 'photo') && <p>{en ? 'Add your first photo to this page.' : 'Ajoutez votre première photo à cette page.'}</p>}</>}</aside>}
    </section><footer className="approval-bar"><label><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span><b>{en ? 'I reviewed every page and approve this exact version for printing.' : 'J’ai relu toutes les pages et j’approuve cette version exacte pour impression.'}</b><small>{en ? `Version ${book.version} · Changes stay available until approval.` : `Version ${book.version} · Les modifications restent possibles jusqu’à la validation.`}</small></span></label><button className="button" disabled={!confirmed || approved} onClick={approve}>{approved ? (en ? 'Approved ✓' : 'Aperçu approuvé ✓') : (en ? 'Approve for printing →' : 'Valider pour impression →')}</button></footer>
    {approved && <div className="approval-success"><span>✓</span><h2>{en ? 'Preview approved.' : 'Aperçu approuvé.'}</h2><p>{en ? 'This exact version was timestamped. You can now follow production from your account.' : 'Cette version exacte a été horodatée. Vous pouvez maintenant suivre la production depuis votre compte.'}</p><Link className="button" href={profile}>{en ? 'Track my order →' : 'Suivre ma commande →'}</Link></div>}
  </main>;
}

function PageContent({ page, book, en }: { page: BookPage; book: GeneratedBook; en: boolean }) {
  const media = page.mediaIds.map((id) => book.media.find((item) => item.id === id)).filter(Boolean); const photo = media.find((item) => item?.kind === 'photo'); const interactive = media.filter((item) => item?.kind !== 'photo');
  if (page.kind === 'cover') return <><small>{page.eyebrow || 'MÉMOIRE MAISON'}</small><h2>{page.title}</h2>{photo?.previewUrl ? <img className="page-main-image" src={photo.previewUrl} alt="" /> : <div className="cover-photo"><span className="mini-house" /></div>}<p>{page.body}</p><small>{book.subtitle}</small></>;
  return <><p className="page-number">{book.pages.findIndex((item) => item.id === page.id) + 1}</p>{page.eyebrow && <p className="eyebrow">{page.eyebrow}</p>}<h3>{page.title}</h3>{photo?.previewUrl && <img className="page-main-image" src={photo.previewUrl} alt="" />}<p>{page.body}</p>{page.quote && <blockquote>{page.quote}</blockquote>}{page.kind === 'interactive' && <div className="voice-qr"><span className="fake-book-qr">▦</span><span>{interactive.length ? `${interactive.length} ${en ? 'living memories' : 'souvenirs vivants'}` : (en ? 'Private family link' : 'Lien privé de la famille')}</span></div>}</>;
}
