'use client';
import { useState } from 'react';
import Link from 'next/link';

const prompts = ['What year did you move into this home?', 'What first made you fall in love with it?', 'What is your earliest memory here?', 'Which room or corner did you love most?', 'What family moment comes to mind first?', 'What celebration did you share here?', 'What story still makes you smile?', 'How did the home change with your family?', 'What will you miss most?', 'How would you sum up your years here?'];
const addOns = [['copy','Family copy','A second identical book',49],['film','“Our Home” mini-film','1–3 minutes from photos and videos',79],['memory','Memory Link + QR card','Private gallery, story, voices and film',39],['frame','Preloaded digital frame','Your photos already installed',129]] as const;

export function EnglishStudio() {
  const [step,setStep]=useState(1); const [title,setTitle]=useState('Our Home'); const [years,setYears]=useState('2008 — 2026'); const [color,setColor]=useState('forest'); const [format,setFormat]=useState('Essential'); const [answers,setAnswers]=useState<Record<number,string>>({}); const [extras,setExtras]=useState<string[]>(['memory']);
  const base=format==='Essential'?149:format==='Keepsake'?199:249; const total=base+addOns.filter(([id])=>extras.includes(id)).reduce((sum,item)=>sum+item[3],0); const toggle=(id:string)=>setExtras((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);
  return <div className="studio-shell"><aside className="studio-sidebar"><Link className="studio-brand" href="/en"><span className="brand-mark">M</span><span>Mémoire<br />Maison</span></Link><p className="studio-kicker">Creation studio</p><ol className="studio-steps">{['Your book','Your story','Your memories','Finishing touches'].map((label,index)=><li key={label} className={step===index+1?'active':step>index+1?'done':''}><button onClick={()=>setStep(index+1)}><span>{step>index+1?'✓':index+1}</span>{label}</button></li>)}</ol><div className="studio-help"><span>♡</span><p><b>Need a hand?</b><br />Émilie and her team are here for you.</p></div></aside><main className="studio-main"><div className="studio-top"><p>Your project saves automatically</p><Link href="/en/profile">Leave and finish later</Link></div><div className="studio-content"><section className="studio-form">
    {step===1?<><p className="eyebrow">Step 1 of 4</p><h1 className="studio-title">Let’s begin with the cover.</h1><p className="studio-intro">You can change everything before printing. Nothing is final today.</p><label className="field-label">Collection</label><div className="choice-grid three">{['Essential','Keepsake','Family'].map((item)=><button className={`choice-card ${format===item?'selected':''}`} key={item} onClick={()=>setFormat(item)}><b>{item}</b><small>{item==='Essential'?'1 book · $149':item==='Keepsake'?'Premium finish · $199':'3 copies · $249'}</small></button>)}</div><label className="field-label" htmlFor="en-book-title">Book title</label><input id="en-book-title" className="studio-input" value={title} onChange={(e)=>setTitle(e.target.value)}/><label className="field-label" htmlFor="en-years">Years or subtitle</label><input id="en-years" className="studio-input" value={years} onChange={(e)=>setYears(e.target.value)}/><label className="field-label">Cover colour</label><div className="swatches">{['forest','clay','linen','midnight'].map((item)=><button aria-label={`${item} colour`} key={item} className={`swatch ${item} ${color===item?'selected':''}`} onClick={()=>setColor(item)}/>)}</div></>:null}
    {step===2?<><p className="eyebrow">Step 2 of 4</p><h1 className="studio-title">Tell it in your own words.</h1><p className="studio-intro">Write the way you would speak to someone you love. Skip anything and return later.</p><div className="question-list">{prompts.map((prompt,index)=><label className="question-card" key={prompt}><span><b>{String(index+1).padStart(2,'0')}</b>{prompt}</span><textarea value={answers[index]||''} onChange={(e)=>setAnswers({...answers,[index]:e.target.value})} placeholder="Your memory…"/><button type="button" className="voice-button">● Answer with my voice</button></label>)}</div></>:null}
    {step===3?<><p className="eyebrow">Step 3 of 4</p><h1 className="studio-title">Add the images that matter.</h1><p className="studio-intro">Up to 20 photos or videos: your home, family, renovations, garden and tiny details.</p><label className="upload-zone"><input type="file" multiple accept="image/*,video/*,audio/*"/><span className="upload-icon">＋</span><b>Drop your photos here</b><small>or click to browse · JPG, PNG, HEIC, MP4</small></label><div className="upload-tips"><h3>What makes a beautiful book</h3><p>A view of the home, loved rooms, everyday moments and details you never want to forget. Perfect quality is not required.</p></div></>:null}
    {step===4?<><p className="eyebrow">Step 4 of 4</p><h1 className="studio-title">Let the memory live on.</h1><p className="studio-intro">Only add what feels right for your family. Extra copies can be ordered later.</p><div className="extras-list">{addOns.map(([id,name,detail,price])=><label className={`extra-card ${extras.includes(id)?'selected':''}`} key={id}><input type="checkbox" checked={extras.includes(id)} onChange={()=>toggle(id)}/><span className="extra-check">{extras.includes(id)?'✓':'+'}</span><span><b>{name}</b><small>{detail}</small></span><strong>+ ${price}</strong></label>)}</div><div className="total-card"><span><small>Estimated total</small><b>{format} + options</b></span><strong>${total} CAD</strong></div></>:null}
  </section><aside className="live-preview"><p>Live preview</p><div className={`preview-book ${color}`}><div className="preview-window"><span className="mini-house"/></div><h2>{title||'Your title'}</h2><small>{years||'Your subtitle'}</small></div><div className="preview-caption"><span>21 × 21 cm</span><span>20 to 30 pages</span></div></aside></div><div className="studio-nav"><button onClick={()=>setStep(Math.max(1,step-1))} disabled={step===1}>← Back</button><span>{step} / 4</span>{step<4?<button className="button" onClick={()=>setStep(step+1)}>Continue →</button>:<Link className="button" href="/en/preview">Generate my preview →</Link>}</div></main></div>;
}
