import Link from './components/SafeLink';
import { SiteFooter, SiteHeader } from './components/SiteHeader';

export default function Home() {
  return <><SiteHeader homeThemes /><main>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">Livres souvenirs personnalisés</p><h1>Chaque maison<br />a une histoire.</h1><p className="hero-lead">Avant de tourner la page, rassemblez les photos, les voix et les petits détails qui ont fait de votre maison un foyer.</p><div className="hero-actions"><Link className="button" href="/atelier">Commencer mon histoire <span>→</span></Link><a className="quiet-link" href="#comment">Découvrir l’expérience <span>↘</span></a></div><div className="hero-note"><span>10</span><p>questions seulement<br />pour commencer</p></div></div><div className="hero-visual" aria-label="Aperçu d’un livre souvenir"><div className="shelf-line" /><div className="book book-back"><span>NOTRE MAISON</span></div><div className="book book-front"><div className="book-photo"><span className="house-roof" /><span className="house-body" /><span className="house-door" /></div><p>Notre Maison</p><small>2008 — 2026</small></div><div className="memory-card"><span>«</span><p>Les murs restent.<br />Les souvenirs partent<br />avec vous.</p></div></div></section>
    <section className="trust-strip"><p><span>01</span> Vos mots, vos souvenirs</p><p><span>02</span> Une création accompagnée</p><p><span>03</span> Votre validation avant impression</p></section>
    <section className="how-section" id="comment"><div className="section-heading"><p className="eyebrow">Simple dès le premier souvenir</p><h2>Vous racontez.<br />Nous en faisons un livre.</h2><p>Pas besoin d’écrire un roman ni de tout préparer. Quelques minutes suffisent pour commencer, et vous gardez le dernier mot à chaque étape.</p></div><div className="steps-grid"><article><span>01</span><div className="step-icon">✎</div><h3>Racontez</h3><p>Dix questions douces, par écrit ou avec votre voix.</p></article><article><span>02</span><div className="step-icon">▧</div><h3>Rassemblez</h3><p>Ajoutez vos photos, vidéos et petits détails précieux.</p></article><article><span>03</span><div className="step-icon">✦</div><h3>Découvrez</h3><p>Nous structurons vos mots sans jamais inventer un souvenir.</p></article><article><span>04</span><div className="step-icon">✓</div><h3>Validez</h3><p>Relisez, modifiez, puis approuvez avant l’impression.</p></article></div><Link className="button outline" href="/atelier">Voir l’atelier de création →</Link></section>
    <section className="collections" id="collections"><div className="section-heading light-heading"><p className="eyebrow">Une collection pour chaque chapitre</p><h2>Les lieux qui<br />nous construisent.</h2></div><div className="collection-grid"><article className="collection-one"><div className="collection-image"><span className="collection-house" /></div><small>Collection 01</small><h3>Notre Maison</h3><p>Pour le lieu que l’on s’apprête à quitter.</p></article><article className="collection-two"><div className="collection-image"><span>01</span><b>Our<br />First<br />Home</b></div><small>Collection 02</small><h3>Notre Première Maison</h3><p>Pour le chapitre où tout a commencé.</p></article><article className="collection-three"><div className="collection-image"><i /><i /><i /></div><small>Collection 03</small><h3>Maison de Famille</h3><p>Pour transmettre l’histoire entre générations.</p></article></div></section>
    <section className="memory-link-section"><div className="memory-device"><div className="phone"><div className="phone-photo"><span>La maison<br />des Érables</span><button>▶</button></div><p>Nos souvenirs</p><div className="phone-thumbs"><i /><i /><i /></div></div><div className="qr-card"><div className="fake-qr">▦</div><span>MEMORY LINK</span><small>La maison des Érables</small></div><div className="key-tag"><span>⌁</span></div></div><div className="memory-link-copy"><p className="eyebrow">Nouveau · Memory Link</p><h2>Le livre se referme.<br />Les souvenirs continuent.</h2><p>Un QR code discret ouvre une archive privée de votre famille : photos, récit, mini-film et même la voix de ceux qui racontent.</p><ul><li><span>✓</span> Une page privée à transmettre aux proches</li><li><span>✓</span> Un lien qui peut évoluer sans réimprimer le QR</li><li><span>✓</span> Carte premium ou porte-clé QR/NFC</li></ul><Link className="quiet-link" href="/memory/demo">Explorer un Memory Link →</Link></div></section>
    <section className="offers-section"><div className="section-heading"><p className="eyebrow">Les livres</p><h2>Choisissez la place<br />que prendra votre histoire.</h2></div><div className="offer-grid"><article><div className="offer-book essential">MM</div><p className="eyebrow">Essentiel</p><h3>Le livre qui rassemble.</h3><p>20 à 30 pages, couverture rigide, aperçu numérique et 1 exemplaire.</p><b>À partir de 149 $</b><Link href="/atelier">Choisir Essentiel →</Link></article><article className="featured-offer"><span className="popular">LE PLUS AIMÉ</span><div className="offer-book souvenir">Notre<br />Maison</div><p className="eyebrow">Souvenir</p><h3>Une finition plus précieuse.</h3><p>Papier premium, détails personnalisés et une copie famille supplémentaire.</p><b>À partir de 199 $</b><Link href="/atelier">Choisir Souvenir →</Link></article><article><div className="offer-book family"><span>Heritage</span></div><p className="eyebrow">Famille</p><h3>Pour partager entre générations.</h3><p>Plusieurs exemplaires, coffret et options d’archive numérique.</p><b>À partir de 249 $</b><Link href="/atelier">Choisir Famille →</Link></article></div></section>
    <section className="story-quote"><div className="quote-image"><div className="polaroid"><span className="family-silhouette">♧</span><small>Le premier été · 2009</small></div></div><div><span className="big-quote">“</span><blockquote>Je pensais que j’allais pleurer en voyant la maison. J’ai surtout souri en redécouvrant tout ce qu’on y avait vécu.</blockquote><p>— Sophie, projet pilote à Québec</p></div></section>
    <section className="b2b-banner"><div><p className="eyebrow">Courtiers & agences</p><h2>Offrez une histoire,<br />pas un objet de plus.</h2><p>Invitez un vendeur en quelques clics. Nous prenons en charge le récit, la création, la validation, l’impression et la livraison.</p><Link className="button light" href="/professionnels">Découvrir l’offre professionnelle →</Link></div><div className="credit-card"><span>VOS CRÉDITS</span><b>25</b><small>expériences à offrir</small><div><i /><i /><i /><i /><i /></div><p>MÉMOIRE MAISON <em>pour Émilie Cauvier</em></p></div></section>
    <section className="faq-section"><div><p className="eyebrow">Questions fréquentes</p><h2>Tout ce qu’il faut<br />savoir avant de commencer.</h2></div><div className="faq-list"><details open><summary>Est-ce que mes souvenirs sont inventés ou modifiés ?<span>−</span></summary><p>Jamais. Nous pouvons fluidifier et organiser vos mots, mais chaque personne, date, événement et émotion doit venir de vos réponses. Vous validez tout avant impression.</p></details><details><summary>Combien de temps faut-il pour répondre ?<span>+</span></summary><p>Environ dix minutes pour commencer. Vous pouvez enregistrer votre progression et revenir plus tard.</p></details><details><summary>Puis-je modifier le livre avant impression ?<span>+</span></summary><p>Oui. L’aperçu numérique vous permet de modifier une réponse, remplacer une photo et approuver la version finale.</p></details><details><summary>Comment fonctionne le Memory Link ?<span>+</span></summary><p>Un QR code ou une puce NFC ouvre une page privée contenant les souvenirs autorisés par la famille.</p></details></div></section>
    <section className="final-cta"><p className="eyebrow">Votre prochain chapitre peut commencer</p><h2>Gardez l’histoire.<br />Emportez-la avec vous.</h2><Link className="button" href="/atelier">Créer mon livre souvenir →</Link></section>
  </main><SiteFooter /></>;
}
