import Link from '../components/SafeLink';
import { BookWheel } from '../components/BookWheel';
import { BookShowcase } from '../components/BookShowcase';
import { SiteFooter, SiteHeader } from '../components/SiteHeader';

const steps = [['01','Tell','Ten gentle questions, in writing or in your own voice.'],['02','Gather','Add the photos, videos and details that make the place unique.'],['03','Discover','Your story takes shape in a complete first proof.'],['04','Approve','Review and edit every page before anything is printed.']];

export default function EnglishHome(){return <><SiteHeader locale="en" homeThemes/><main className="home-page">
  <BookShowcase locale="en" />
  <section className="trust-strip"><p><span>01</span>Your words, your memories</p><p><span>02</span>A guided creation</p><p><span>03</span>Your approval before print</p></section>
  <section className="premium-process" id="how"><div className="section-heading"><p className="eyebrow">Simple from the first memory</p><h2>You tell it.<br/><em>We compose it.</em></h2><p>Begin in minutes, add memories at your own pace and keep the final word at every step.</p></div><div className="premium-steps">{steps.map(([number,title,text])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><Link className="button outline" href="/en/studio">Discover the studio →</Link></section>
  <section className="premium-collection" id="collections"><div className="collection-heading"><p className="eyebrow">Three ways to pass it on</p><h2>A collection designed<br/>like an editorial object.</h2></div><figure><img src="/memory-book-collection-v2.jpg" alt="A collection of ivory, burgundy and midnight-blue memory books"/><figcaption>Ivory linen · Deep burgundy · Midnight blue</figcaption></figure><div className="collection-notes"><p><b>Our Home</b>For the place you are about to leave.</p><p><b>Our First Home</b>For the chapter where everything began.</p><p><b>Family Home</b>For a story passed through generations.</p></div></section>
  <section className="premium-memory-link"><div className="memory-photo-wrap"><img src="/memory-link-v2.jpg" alt="Open photo book and private Memory Link on a phone"/><Link href="/en/memory/demo" aria-label="Explore the Memory Link"><span>→</span> View the demonstration</Link></div><div className="memory-link-copy"><p className="eyebrow">New · Memory Link</p><h2>The book closes.<br/><em>The memories live on.</em></h2><p>A discreet QR code opens your family’s private archive: photographs, mini-film, story and the voices behind it.</p><ul><li><span>✓</span>A private page to share with loved ones</li><li><span>✓</span>A link that evolves without reprinting the QR</li><li><span>✓</span>Premium card or QR/NFC keepsake tag</li></ul><Link className="quiet-link" href="/en/memory/demo">Explore a Memory Link →</Link></div></section>
  <BookWheel locale="en" />
  <section className="premium-story"><div className="story-photo"><img src="/family-memories-v2.jpg" alt="A family looking through photographs before moving"/><span>The memories that follow us</span></div><div className="story-copy"><span className="big-quote">“</span><blockquote>I thought seeing the house would make me cry. Instead, I smiled as I rediscovered everything we had lived there.</blockquote><p>— Sophie, Québec pilot project</p></div></section>
  <section className="premium-professionals"><div><p className="eyebrow">Realtors & agencies</p><h2>Give a story,<br/>not one more object.</h2><p>A deeply personal closing experience, handled from the invitation through delivery.</p><Link className="button light" href="/en/professionals">The professional offer →</Link></div></section>
  <section className="faq-section"><div><p className="eyebrow">Frequently asked questions</p><h2>Before you<br/>begin.</h2></div><div className="faq-list"><details open><summary>Will my memories be invented or changed?<span>−</span></summary><p>Never. We may organize and polish your words, but every person, date and feeling comes from you. You approve everything before print.</p></details><details><summary>How long does it take?<span>+</span></summary><p>About ten minutes to begin. Save your progress and return whenever you wish.</p></details><details><summary>Can I edit before printing?<span>+</span></summary><p>Yes. Replace a photo, revise a text and approve the exact version that will be printed.</p></details></div></section>
  <section className="premium-final"><img src="/quebec-home-v2.jpg" alt="A Québec family home at sunset"/><div><p className="eyebrow">Your next chapter can begin</p><h2>Keep the story.<br/>Take it with you.</h2><Link className="button light" href="/en/studio">Create my memory book →</Link></div></section>
  </main><SiteFooter locale="en"/></>}
