import type {Metadata} from 'next';
import Link from '../../components/SafeLink';
import {SiteFooter,SiteHeader} from '../../components/SiteHeader';
export const metadata:Metadata={title:'Closing gifts for realtors — Mémoire Maison',description:'Offer sellers a personalized memory book of their home with a simple professional workflow.'};
export default function EnglishProfessionals(){return <><SiteHeader locale="en"/><main className="pro-page">
  <section className="pro-hero"><div><p className="eyebrow">For real estate professionals</p><h1>A closing gift unlike any other.</h1><p>Give sellers a deeply personal experience without adding work to your team.</p><div className="hero-actions"><a className="button" href="#packs-en">Explore plans →</a><a className="quiet-link" href="mailto:emilie@equipecauvier.com">Talk to Emilie</a></div></div><div className="pro-portal-card"><div className="portal-head"><span>Professional portal</span><b>12 credits</b></div><h3>Hello, Beaulieu Team</h3><p>Your closing gifts, made simple.</p><div className="portal-metrics"><span><b>8</b>in progress</span><span><b>3</b>to approve</span><span><b>17</b>delivered</span></div><button>＋ Invite a seller</button></div></section>
  <section className="pro-benefits"><p className="eyebrow">Why it works</p><h2>More than an object. A beautiful final step in the transaction.</h2><div><article><span>01</span><h3>You invite</h3><p>Name, address and email are all you need.</p></article><article><span>02</span><h3>The family tells</h3><p>They answer, add media and approve their book.</p></article><article><span>03</span><h3>We produce</h3><p>Story, review, layout, printing and shipping are handled.</p></article><article><span>04</span><h3>You stay remembered</h3><p>Your message joins a keepsake that lasts for years.</p></article></div></section>
  <section className="packs" id="packs-en"><div className="section-heading"><p className="eyebrow">Credit packs</p><h2>An offer built around your volume.</h2><p>Each credit funds one individual Essential book: one seller, one project, one print-on-demand copy.</p></div><div className="pack-grid"><article><small>DISCOVERY</small><h3>10 credits</h3><p>$139 per seller.</p><b>$1,390 CAD</b><Link href="/professionnels/inscription">Create the account →</Link></article><article className="featured"><small>MOST POPULAR</small><h3>25 credits</h3><p>$130 per seller.</p><b>$3,250 CAD</b><Link href="/professionnels/inscription">Create the account →</Link></article><article><small>AGENCY</small><h3>50 credits</h3><p>$125 per seller.</p><b>$6,250 CAD</b><Link href="/professionnels/inscription">Create the account →</Link></article></div><p className="pro-billing-note"><b>Professional portal:</b> $49/month or $490/year (two months free). Taxes extra. Renewal may be cancelled before the next billing date.</p></section>
  <section className="pro-cta"><p className="eyebrow">Québec pilot program · Fall 2026</p><h2>Become one of our first<br/>professional partners.</h2><Link className="button light" href="/professionnels/inscription">Create an agency account →</Link></section>
</main><SiteFooter locale="en"/></>}
